name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dotenv: ^3.0.0
  mysql1: ^0.20.0
  get_it: ^7.2.0
  logger: ^1.2.2
  injectable: ^2.1.0
  jaguar_jwt: ^3.0.0
  http: ^0.13.6  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  shelf_router_generator: ^1.0.5
  
